# Generated by Django 5.0.6 on 2024-06-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_location_ip_address_alter_location_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
    ]
